# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'temp.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from second import Ui_SecondWindow

class Ui_MainWindow(object):
    def __init__(self):
        self.Labels_Holes = []
        self.Edit_Holes = []
        self.Edit_Size = []
        self.Labels = []
        self.Push = []
        self.big = []
        self.font=QtGui.QFont()
        self.font.setFamily("Niagara Solid")
        self.font.setPointSize(18) 
    def openWindow(self,holes,size):
        self.window=QtWidgets.QMainWindow()
        self.ui = Ui_SecondWindow()
        self.ui.setupUi(self.window)
        self.ui.parameters(holes,size)
        self.window.show()
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1111, 832)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(-10, 0, 1111, 81))
        font = QtGui.QFont()
        font.setFamily("Niagara Solid")
        font.setPointSize(18)
        font.setBold(False)
        font.setWeight(50)
        self.frame.setFont(font)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(10, 0, 161, 71))
        font = QtGui.QFont()
        font.setFamily("Niagara Solid")
        font.setPointSize(18)
        font.setBold(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.lineEdit = QtWidgets.QLineEdit(self.frame)
        self.lineEdit.setGeometry(QtCore.QRect(160, 20, 161, 31))
        self.lineEdit.setObjectName("lineEdit")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setGeometry(QtCore.QRect(440, 20, 141, 21))
        self.label_2.setObjectName("label_2")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_2.setGeometry(QtCore.QRect(590, 20, 141, 31))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.pushButton = QtWidgets.QPushButton(self.frame)
        self.pushButton.setGeometry(QtCore.QRect(830, 10, 171, 41))
        self.pushButton.setObjectName("pushButton")
        self.line = QtWidgets.QFrame(self.frame)
        self.line.setGeometry(QtCore.QRect(120, 70, 901, 21))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 90, 1091, 701))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1111, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.pushButton.clicked.connect(self.clicked_hole)
        
    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Total Memory Size : "))
        self.label_2.setText(_translate("MainWindow", "Number of Holes:"))
        self.pushButton.setText(_translate("MainWindow", "Submit"))
        
    def clicked_hole(self):
        #self.gridLayout.setVerticalSpacing(40)
        self.gridLayout.setSizeConstraint(40)
        holes_number = int(self.lineEdit_2.text())
        #Labels
        Label_Ad = QtWidgets.QLabel(self.gridLayoutWidget)
        Label_Ad.setFont(self.font)
        Label_Ad.setText("Starting Address")
      #  self.gridLayout.addWidget(Label_Ad,0,2)
        Label_Size = QtWidgets.QLabel(self.gridLayoutWidget)
        Label_Size.setFont(self.font)
        Label_Size.setText("Size")
       # self.gridLayout.addWidget(Label_Size,0,3)
        # Push Button
        self.Push.append(QtWidgets.QPushButton(self.gridLayoutWidget))
        self.Push[0].setFont(self.font)
        self.Push[0].setText("Submit")
        self.gridLayout.addWidget(self.Push[0],2+holes_number,3)
        self.Push[0].clicked.connect(self.hole_info)

        for i in range(holes_number):
            self.Labels_Holes.append(QtWidgets.QLabel(self.gridLayoutWidget))
            self.Labels_Holes[i].setFont(self.font)
            self.Labels_Holes[i].setText(f"Hole {i+1}: Starting Address - Size")
            self.gridLayout.addWidget(self.Labels_Holes[i],i+2,1)

            self.Edit_Holes.append(QtWidgets.QLineEdit(self.gridLayoutWidget))
            self.Edit_Holes[i].setFont(self.font)
            self.gridLayout.addWidget(self.Edit_Holes[i],i+2,2)

            self.Edit_Size.append(QtWidgets.QLineEdit(self.gridLayoutWidget))
            self.Edit_Size[i].setFont(self.font)
            self.gridLayout.addWidget(self.Edit_Size[i],i+2,3)

    def hole_info(self):
        holes_number = int(self.lineEdit_2.text())
        total_size = int(self.lineEdit.text())
        for i in range(holes_number):
            small = []
            small.append(int(self.Edit_Holes[i].text()))
            small.append(int(self.Edit_Size[i].text()))
            self.big.append(small)
        
        self.openWindow(self.big,total_size)
        MainWindow.hide()

        
    


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
