# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'second.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from plot import *
from initial import *
from first_fit import *
from dealloc import *
from compaction import *
from best_fit import *
from worst_fit import *
from plot import *
import matplotlib.pyplot as plt
import copy
class Ui_SecondWindow(object):
    def __init__(self):
        self.Labels_Holes = []
        self.Edit_Name = []
        self.Edit_Size = []
        self.Labels = []
        self.Push = []
        self.big = []
        self.size = 0
        self.font=QtGui.QFont()
        self.font.setFamily("Niagara Solid")
        self.font.setPointSize(18) 
        self.mem=[]
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1103, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(0, 0, 1101, 61))
        font = QtGui.QFont()
        font.setFamily("Niagara Solid")
        font.setPointSize(18)
        self.frame.setFont(font)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label_4 = QtWidgets.QLabel(self.frame)
        self.label_4.setGeometry(QtCore.QRect(320, 10, 171, 41))
        self.label_4.setObjectName("label_4")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_3.setGeometry(QtCore.QRect(140, 20, 161, 31))
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.label_3 = QtWidgets.QLabel(self.frame)
        self.label_3.setGeometry(QtCore.QRect(20, 10, 171, 41))
        self.label_3.setObjectName("label_3")
        self.pushButton_2 = QtWidgets.QPushButton(self.frame)
        self.pushButton_2.setGeometry(QtCore.QRect(920, 20, 171, 31))
        self.pushButton_2.setObjectName("pushButton_2")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_4.setGeometry(QtCore.QRect(460, 20, 161, 31))
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.comboBox = QtWidgets.QComboBox(self.frame)
        self.comboBox.setGeometry(QtCore.QRect(680, 20, 191, 31))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 80, 901, 381))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(130, 60, 901, 21))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setGeometry(QtCore.QRect(0, 470, 1101, 81))
        font = QtGui.QFont()
        font.setFamily("Niagara Solid")
        font.setPointSize(18)
        self.frame_2.setFont(font)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.push_compaction = QtWidgets.QPushButton(self.frame_2)
        self.push_compaction.setGeometry(QtCore.QRect(540, 30, 551, 41))
        self.push_compaction.setObjectName("push_compaction")
        self.label = QtWidgets.QLabel(self.frame_2)
        self.label.setGeometry(QtCore.QRect(10, 20, 141, 61))
        self.label.setObjectName("label")
        self.lineEdit = QtWidgets.QLineEdit(self.frame_2)
        self.lineEdit.setGeometry(QtCore.QRect(120, 30, 131, 41))
        self.lineEdit.setObjectName("lineEdit")
        self.push_deallocate = QtWidgets.QPushButton(self.frame_2)
        self.push_deallocate.setGeometry(QtCore.QRect(320, 30, 111, 41))
        self.push_deallocate.setObjectName("push_deallocate")
        self.line_2 = QtWidgets.QFrame(self.frame_2)
        self.line_2.setGeometry(QtCore.QRect(110, 0, 901, 21))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(920, 420, 171, 41))
        font = QtGui.QFont()
        font.setFamily("Niagara Solid")
        font.setPointSize(18)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setObjectName("pushButton_3")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1103, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.pushButton_2.clicked.connect(self.clicked_process)
        self.push_compaction.clicked.connect(self.clicked_compaction)
        self.push_deallocate.clicked.connect(self.clicked_deallocation)
        self.pushButton_3.clicked.connect(self.clicked_info)

        self.gridLayout.setVerticalSpacing(20)
        self.gridLayout.setHorizontalSpacing(40)
    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_4.setText(_translate("MainWindow", "Segments Number:"))
        self.label_3.setText(_translate("MainWindow", "Process Name:"))
        self.pushButton_2.setText(_translate("MainWindow", "Submit"))
        self.comboBox.setItemText(0, _translate("MainWindow", "Method of Allocation"))
        self.comboBox.setItemText(1, _translate("MainWindow", "Best Fit"))
        self.comboBox.setItemText(2, _translate("MainWindow", "First Fit"))
        self.comboBox.setItemText(3, _translate("MainWindow", "Worst Fit"))
        self.push_compaction.setText(_translate("MainWindow", "Compaction"))
        self.label.setText(_translate("MainWindow", "Process Name:"))
        self.push_deallocate.setText(_translate("MainWindow", "Deallocate"))
        self.pushButton_3.setText(_translate("MainWindow", "Submit"))
    def clicked_process(self):
        segments_number = int(self.lineEdit_4.text())
        
        
        #Labels
        Label_Ad = QtWidgets.QLabel(self.gridLayoutWidget)
        Label_Ad.setFont(self.font)
        Label_Ad.setText("Segment Name")
        self.gridLayout.addWidget(Label_Ad,0,0)

        Label_Size = QtWidgets.QLabel(self.gridLayoutWidget)
        Label_Size.setFont(self.font)
        Label_Size.setText("Size")
        self.gridLayout.addWidget(Label_Size,0,1)
        
        if segments_number < self.size:
            i=len(self.Edit_Name) - 1
            print(f"i ={i} ")
            while i >= segments_number:
                self.Edit_Name[i].hide()
                self.Edit_Size[i].hide()
                i = i-1
        elif segments_number > self.size and segments_number > len(self.Edit_Name):

            for i in range(self.size):
                self.Edit_Name[i].show()
                self.Edit_Name[i].clear()
                self.Edit_Size[i].show()
                self.Edit_Size[i].clear()
                #print("Loop1")
            
            for i in range(self.size,segments_number):
                self.Edit_Name.append(QtWidgets.QLineEdit(self.gridLayoutWidget))
                self.Edit_Name[i].setFont(self.font)
                self.gridLayout.addWidget(self.Edit_Name[i],i+1,0)

                self.Edit_Size.append(QtWidgets.QLineEdit(self.gridLayoutWidget))
                self.Edit_Size[i].setFont(self.font)
                self.gridLayout.addWidget(self.Edit_Size[i],i+1,1)
                #print("Loop2")
        elif segments_number > self.size and segments_number <= len(self.Edit_Name):
            for i in range(segments_number):
                self.Edit_Name[i].show()
                self.Edit_Name[i].clear()
                self.Edit_Size[i].show()
                self.Edit_Size[i].clear()
                #print("Loop 3")
        self.size = segments_number
    
    def clicked_compaction(self):
        self.mem = compaction(self.mem)
        plt.close()
        plot(self.mem)
        print("I'm in Compaction")

    def clicked_deallocation(self):
        process = self.lineEdit.text()
        self.mem = deallocate(process,self.mem)
        plt.close()
        plot(self.mem)
        print(process)
        print("I'm in Deallocation")
    def parameters(self,holes,size):
        list_holes = holes
        memory_size = size
        mem = intialAlloc(memory_size,list_holes)
        self.mem = mem
        print("111")
        plot(self.mem)
        print("222")
        print(self.mem)

    def clicked_info(self):
        segments_number= int(self.lineEdit_4.text())
        process = self.lineEdit_3.text()
        print(process)
        big = []
        for i in range(segments_number):
            small = []
            name = self.Edit_Name[i].text()
            size= int(self.Edit_Size[i].text())
            small.append(name)
            small.append(size)
            big.append(small)
            

        index = int(self.comboBox.currentIndex())
        if index == 1: # Best Fit
            done, self.mem = bestFit(self.mem, big, process)
        elif index ==2: # Fit First
            done, self.mem = firstFit(self.mem, big, process)
        elif index ==3: # Worst Fit
            done, self.mem = worstFit(self.mem, big, process)
        plt.close()
        plot(self.mem)
        print(done)
        print(self.mem)



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_SecondWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())